/* This file was generated by the Hex-Rays decompiler version 8.0.0.220729.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 __fastcall sub_400700(); // weak
// int puts(const char *s);
// int system(const char *command);
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// unsigned int alarm(unsigned int seconds);
// ssize_t read(int fd, void *buf, size_t nbytes);
// __sighandler_t signal(int sig, __sighandler_t handler);
// void *malloc(size_t size);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int atoi(const char *nptr);
// void __noreturn exit(int status);
void __fastcall __noreturn start(__int64, __int64, void (*)(void));
signed __int64 deregister_tm_clones(); // idb
__int64 register_tm_clones(void); // idb
signed __int64 _do_global_dtors_aux();
__int64 __fastcall frame_dummy();
void __noreturn handler();
unsigned __int64 setup();
int read_int32();
unsigned __int64 create_user();
int print_user();
unsigned __int64 edit_usr();
int print_menu();
int win();
int __cdecl main(int argc, const char **argv, const char **envp);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void _libc_csu_fini(void); // idb
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
__int64 (*qword_602010)(void) = NULL; // weak
_UNKNOWN _bss_start; // weak
_UNKNOWN unk_60208F; // weak
FILE IO_2_1_stdout_; // idb
FILE IO_2_1_stdin_; // idb
char completed_7561; // weak
__int64 cur; // weak


//----- (00000000004006E8) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return _gmon_start__();
  return result;
}
// 6022E0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000400700) ----------------------------------------------------
__int64 sub_400700()
{
  return qword_602010();
}
// 400700: using guessed type __int64 __fastcall sub_400700();
// 602010: using guessed type __int64 (*qword_602010)(void);

//----- (00000000004007D0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(main, v4, &retaddr, _libc_csu_init, _libc_csu_fini, a3, &v5);
  __halt();
}
// 4007D6: positive sp value 8 has been found
// 4007DD: variable 'v3' is possibly undefined

//----- (0000000000400800) ----------------------------------------------------
signed __int64 deregister_tm_clones()
{
  signed __int64 result; // rax

  result = &unk_60208F - &_bss_start;
  if ( (&unk_60208F - &_bss_start) > 0xE )
    return 0LL;
  return result;
}

//----- (0000000000400840) ----------------------------------------------------
__int64 register_tm_clones(void)
{
  return 0LL;
}

//----- (0000000000400880) ----------------------------------------------------
signed __int64 _do_global_dtors_aux()
{
  signed __int64 result; // rax

  if ( !completed_7561 )
  {
    result = deregister_tm_clones();
    completed_7561 = 1;
  }
  return result;
}
// 602260: using guessed type char completed_7561;

//----- (00000000004008A0) ----------------------------------------------------
__int64 __fastcall frame_dummy()
{
  return register_tm_clones();
}
// 4008A0: could not find valid save-restore pair for rbp

//----- (00000000004008C6) ----------------------------------------------------
void __noreturn handler()
{
  exit(1);
}

//----- (00000000004008D4) ----------------------------------------------------
unsigned __int64 setup()
{
  char s[4104]; // [rsp+0h] [rbp-1010h] BYREF
  unsigned __int64 v2; // [rsp+1008h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  memset(s, 0, 0x20uLL);
  setvbuf(&IO_2_1_stdout_, 0LL, 2, 0LL);
  setvbuf(&IO_2_1_stdin_, 0LL, 2, 0LL);
  signal(14, handler);
  alarm(0x3Cu);
  return __readfsqword(0x28u) ^ v2;
}
// 4008D4: using guessed type char s[4104];

//----- (000000000040096F) ----------------------------------------------------
int read_int32()
{
  char buf[40]; // [rsp+0h] [rbp-30h] BYREF
  unsigned __int64 v2; // [rsp+28h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  read(0, buf, 0x20uLL);
  return atoi(buf);
}

//----- (00000000004009BE) ----------------------------------------------------
unsigned __int64 create_user()
{
  void *s; // [rsp+0h] [rbp-1060h] BYREF
  unsigned __int64 v2; // [rsp+1058h] [rbp-8h]

  v2 = __readfsqword(0x28u);
  if ( !s )
  {
    s = malloc(0x20uLL);
    memset(s, 0, 0x20uLL);
  }
  printf("Name: ");
  read(0, s, 0x20uLL);
  printf("Age: ");
  read_int32();
  cur = &s;
  return __readfsqword(0x28u) ^ v2;
}
// 40096F: using guessed type __int64 read_int32(void);
// 602268: using guessed type __int64 cur;

//----- (0000000000400A79) ----------------------------------------------------
int print_user()
{
  int result; // eax

  result = cur;
  if ( cur )
  {
    printf("User: %s\n", *cur);
    return printf("Age: %d\n", *(cur + 72));
  }
  return result;
}
// 602268: using guessed type __int64 cur;

//----- (0000000000400AC9) ----------------------------------------------------
unsigned __int64 edit_usr()
{
  __int64 v0; // rbx
  unsigned __int64 v2; // [rsp+1018h] [rbp-18h]

  v2 = __readfsqword(0x28u);
  if ( cur )
  {
    printf("Name: ");
    read(0, *cur, 0x20uLL);
    printf("Age: ");
    v0 = cur;
    *(v0 + 72) = read_int32();
  }
  return __readfsqword(0x28u) ^ v2;
}
// 602268: using guessed type __int64 cur;

//----- (0000000000400B5E) ----------------------------------------------------
int print_menu()
{
  return puts("Menu:\n1. Create user.\n2. Print user.\n3. Edit user.\n4. Exit.");
}

//----- (0000000000400B71) ----------------------------------------------------
int win()
{
  return system("cat flag");
}

//----- (0000000000400B84) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  int int32; // eax

  setup(argc, argv, envp);
  puts("SUS - Single User Storage.");
  while ( 1 )
  {
    while ( 1 )
    {
      print_menu();
      printf("> ");
      int32 = read_int32();
      if ( int32 != 1 )
        break;
      create_user();
    }
    if ( int32 <= 1 )
      break;
    if ( int32 == 2 )
    {
      print_user();
    }
    else if ( int32 == 3 )
    {
      edit_usr();
    }
    else
    {
LABEL_13:
      puts("Invalid");
    }
  }
  if ( int32 )
    goto LABEL_13;
  return 0;
}
// 4008D4: using guessed type __int64 __fastcall setup(_QWORD, _QWORD, _QWORD);
// 40096F: using guessed type __int64 read_int32(void);
// 4009BE: using guessed type __int64 create_user(void);
// 400A79: using guessed type __int64 print_user(void);
// 400AC9: using guessed type __int64 edit_usr(void);
// 400B5E: using guessed type __int64 print_menu(void);

//----- (0000000000400C10) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  v4 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  init_proc();
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      (_frame_dummy_init_array_entry[i])(a1, a2, a3);
  }
}
// 4006E8: using guessed type __int64 init_proc(void);
// 601E08: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry[2])();
// 601E10: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000400C84) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=45 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
